<html>
<head>
<title>WebKickstart Change Log</title>
</head>
<body>

<h1>WebKickstart Change Log</h1>

<ul>
<li>Glaring bugs in the check.py script are fixed.</li>
<li>The docs for the 'use' keyword have been cleared up a bit.  Need
to be carefull about current directories and paths.</li>
<li>Implemented including scripts in the config files after a '%post'
key.  See the examples above.</li>
<li>Completely changed how mouse configuration is done.  This now
works with all types of mice that the Red Hat Kickstart stuff knows
of.  See the docs.</li>
<li>Added support for the 8.0 RK.  The version string is "8.0".</li>
<li>02/14/03 - 
Moved the Debug Tool to a WRAP'd directory that's served from 
secure.linux.ncsu.edu to protect the information while you are debuging.</li>
<li>02/14/03 - 
We do not send a default kickstart anymore if there is no config
file.  You must have a config file.</li>
<li>02/14/03 - 
Moved to permanent location in AFS.</li>
<li>04/14/03 - 
Added support for the NCSU Realm Kit for Red Hat Linux 9 AKA Shreak.  The
version string is "9".</li>
<li>04/24/03 -
Added RK 9 boot CD.</li>
<li>05/08/03 -
Added "enable safepartition" key and changed the default size of /var/cache
to 512MB, /var to 390 and /boot to 75.  I've also added a new option to the src key and changed the
default to that option of "http" which installs from install.linux.ncsu.edu.</li>
<li>06/05/03 -
Added "enable keepmbr" which doesn't overwrite the MBR with the bootloader.
The bootloader is placed in the boot partition (/boot).</li>
<li>06/20/03 -
Implemented "owner" key.  Fixed % handling so that anything after a line
beginning with "%" is included, including that % line.  This makes adding
%post, %pre, etc a bit more useful as you can pass options to them.  Fixed 
case where the use keyword is used more than once.  Fixed the growing URL problem when the Reinstall Workstation boot option is used.</li>
<li>08/26/03 -
RAID and LVM support for versions 9 and higher.  The part, raid, volgroup,
and logvol keys are all used just as you would use them in a Red Hat
Kickstart.  An example provided.</li>
<li>09/02/03 -
Check for and only serve a kickstart to Anaconda not just any HTTP client.
Web-kickstart installs are now logged into a MySQL database.</li>
<li>09/09/03 -
The functionality of the 'users' keyword has been changed.  Currently,
using this keyword will do nothing.  To specify additional admin users
you should now use the 'enable adminusers [user[, user ... ]]' key.  The
'users' key will be changed to behave identically to the Solaris version
RSN.  Also, there is now no way to override pulling an admin user list
from AFS, but 'enable adminusers' will add to this list.</li>
<li>10/10/03 -
Changed the 'root' key to 'rootpw'.  The root key will have new functionality
similar to that of the Solaris config files in the future.  </li>
<li>11/21/03 -
Added support for Realm Linux FC1.  The version string to use is "FC1"
</li>
<li>12/31/03 -
Fixed #286 which makes the 'use' keyword much more saner.  Top level configs
override included configs and top level %posts come after included %posts.
Also changed the system so that admin users and root passwords are pulled
from Jeff's "new" update system.  See /afs/bp/system/common/update/.
</li>
<li>3/8/04 -
Fixed #296 which adds the key 'enable staticip' to configure a client
with a static IP address rather than DHCP.  See the documentation
for exact usage.  Note that web-kickstart will requires DHCP to get
the kickstart to the client.</li>

</ul>

</body>
</html>

