<html>
<head>
<title>Jump Start for the Linux Realm Kit</title>
</head>
<body>

<h1>Jump Start for the Linux Realm Kit</h1>

<p>Red Hat Linux uses an automated install system known as Kickstart.
Very basically, this is a detailed text file that the Red Hat Linux
installer can retrieve and use to install the machine rather than
asking the a human many questions.  One of the most powerful methods
of delivering a kickstart file to the installer is by HTTP which
allows complex scripting to generate the proper kickstart file.  This
is what we are doing here.</p>

<p>The Solaris Kit on campus uses the Solaris equivalent known as Jump
Start which has a few key advantages.  First, its well known and
understood around campus, it uses include files much more easily that
kickstart can, and most common configurations can be done in four or
five lines rather than hundreds.  Hence, this system was developed to
take a config file in the form of a Solaris Jump Start, convert it to
a Red Hat Kickstart, and HTTP it directly to the requesting client for
installation.</p>

<p>Maintained by <a href="mailto:linux@help.ncsu.edu">Jack Neely</a>.</p>

<h2>Documentation</h2>

<p>This system is designed to generate a <a
href="http://www.redhat.com/docs/manuals/linux/RHL-7.3-Manual/custom-guide/ch-kickstart2.html">Red
Hat Linux Kickstart</a> to install the <a
href="http://www.linux.ncsu.edu/realmkit">NCSU Realm Kit for Red Hat
Linux</a>.  A config file can be used to customize the kickstart that
is delivered.  There are two ways to produce a config file.  A normal
kickstart file can be used or a Jump Start style config file can also
be used.  The files must be named the same as the target computers
hostname.  Files must be placed under the following directory:</p>
 
<tt>/afs/bp/system/config/linux-kickstart/configs</tt>.

<p><b>Note:</b> Using a jump start config file to install the NCSU Realm 
Kit for Red hat Linux has two requirements.  First, the machine must be 
configured to use DHCP.  Secondly, its IP address received from DHCP must 
resolve to a domain name.</p>

<h3>Examples and More Documentation.</h3>
<ul>
<li><a href="docs/keywords.txt">keywords.txt</a> - List of all
keywords, their syntax, and what they will do.</li>
<li><a href="docs/design.txt">design.txt</a> - A rough design
document.</li>
<li><a href="http://www.redhat.com/docs/manuals/linux/RHL-9-Manual/custom-guide/ch-kickstart2.html">Red
Hat Linux Kickstart Documentation</li>
<li><a
href="http://www.redhat.com/docs/manuals/linux/RHL-7.3-Manual/custom-guide/s1-kickstart2-options.html">
Red Hat Linux Kickstart Options (7.3)</li>
<li><a
href="http://www.redhat.com/docs/manuals/linux/RHL-9-Manual/custom-guide/s1-kickstart2-options.html">
Red Hat Linux Kickstart Options (9)</li>
<li><a
href="examples/rk-test3.pams.ncsu.edu">rk-test3.pams.ncsu.edu</a> - An
example.</li>
<li><a href="examples/script1">script1</a> - config file included by
the above config file.</li>
<li><a href="examples/lvm">LVM</a> - A short example on using LVM.</li>
</ul>

<h3>Disk Image</h3>
<p>Here's a disk image that is set up to automatically do a
kickstart install from web-kickstart.linux.ncsu.edu.  (This was done
by modifying the syslinux.cfg file on the floppy.</p>
<ul>
<li><a href="9-web-ks.iso">9-web-ks.iso</a> - RK 9 Boot CD</li>
<li><a href="9-web-ks-eth0.iso">9-web-ks-eth0.iso</a> - RK 9 Boot CD For 
Systems with Multiple Ethernet Cards this Image Uses eth0</li>
<li><a href="9-web-ks.iso">FC1-web-ks.iso</a> - RK FC1 Boot CD</li>
</ul>

<h3>Recent Changes</h3>

<p>The following are some recent changes to the system there were made
after I released it to public testing.  These changes are also
documented in the <a href="docs/keywords.txt">keywords.txt</a> file or
their relivant place.</p>

<p>The <a href="changelog.phtml">Change Log</a> has grown quite a bit so 
I've moved it to its own page.
Please keep up with the systems as it grows and changes.</p>

<h2>Debuging Tool</h2>
<p>
For security reasons the debuging tool has been moved to a WRAP protected
directory.  Please email <a href="mailto:linux@help.ncsu.edu">
linux@help.ncsu.edu</a> if you are not on the access list and think you
should be.  Otherwise, 
<a href="https://secure.linux.ncsu.edu/web-kickstart/WRAP/index.html">
start debuging</a>.
</p>

</body>
</html>
